/**
 * Writes the script's generated modules from the lists in this folder:
 *
 * - `src/generated/layout.ts` from `preset-fields.ts`: a const enum of byte
 *   offsets, a const enum of switch bits, and the record's size
 * - `src/generated/menu.ts` from `menu-buttons.ts`: a const enum of buttons,
 *   and their labels in the order `ll.Dialog` lays them out
 *
 * It lives outside `src`, so the compiler never reads it and none of it
 * reaches the script. `bun run build` runs it before every build.
 */
import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { ROWS } from "./menu-buttons"
import { FIELDS } from "./preset-fields"

const HEADER = (list: string) => `// Generated by tools/generate.ts from tools/${list}.
// Run \`bun run generate\` after changing that list. Don't edit this file.
`

const pascal = (name: string) => name[0].toUpperCase() + name.slice(1)

function repeated(names: readonly string[]) {
  return names.filter((name, index) => names.indexOf(name) !== index)
}

function layout() {
  const WIDTHS = { byte: 1, percent: 1, u16: 2 } as const
  const twice = repeated(FIELDS.map((field) => field.name))

  if (twice.length > 0) {
    throw new Error(`Repeated field names: ${twice.join(", ")}`)
  }

  const flags = FIELDS.filter((field) => field.kind === "flag")

  if (flags.length > 8) {
    throw new Error(`${flags.length} flags don't fit in one byte`)
  }

  const offsets: string[] = []
  let size = 0

  for (const field of FIELDS) {
    if (field.kind === "flag") {
      continue
    }

    offsets.push(`  ${pascal(field.name)} = ${size},`)
    size += WIDTHS[field.kind]
  }

  if (flags.length > 0) {
    offsets.push(`  Flags = ${size},`)
    size += 1
  }

  const bits = flags.map((field, index) => `  ${pascal(field.name)} = ${1 << index},`)

  return `${HEADER("preset-fields.ts")}
/** Each field's byte offset in a preset buffer. */
export const enum Offset {
${offsets.join("\n")}
}

/** Each switch's bit in the Flags byte. */
export const enum Flag {
${bits.join("\n")}
}

/** Bytes in one preset buffer. */
export const PRESET_BYTES = ${size}
`
}

function menu() {
  // ll.Dialog fills rows of three from the bottom left, so the bottom row comes first
  const buttons = ROWS.toReversed().flat()

  if (buttons.length > 12) {
    throw new Error(`${buttons.length} buttons don't fit in one menu`)
  }

  const twice = [
    ...repeated(buttons.map((button) => button.name)),
    ...repeated(buttons.map((button) => button.label)),
  ]

  if (twice.length > 0) {
    throw new Error(`Repeated buttons: ${twice.join(", ")}`)
  }

  const long = buttons.filter((button) => new TextEncoder().encode(button.label).length > 24)

  if (long.length > 0) {
    throw new Error(`Labels over 24 bytes: ${long.map((b) => b.label)}`)
  }

  return `${HEADER("menu-buttons.ts")}
/** Each button's position in \`LABELS\`, which is what a reply is matched against. */
export const enum Button {
${buttons.map((button, index) => `  ${button.name} = ${index},`).join("\n")}
}

/** What the menu shows, in \`ll.Dialog\` order. */
export const LABELS = [
${buttons.map((button) => `  ${JSON.stringify(button.label)},`).join("\n")}
]
`
}

async function write(file: string, source: string) {
  const path = resolve(import.meta.dir, "../src/generated", file)

  // Rewrite only on a change, so a watch build doesn't see a new file each time
  if ((await readFile(path, "utf8").catch(() => "")) === source) {
    return
  }

  await writeFile(path, source)
  console.log(`Wrote ${path}`)
}

await write("layout.ts", layout())
await write("menu.ts", menu())
